//! Exact rank boundaries and deterministic reversible message vectors.
use super::*;
use rand::{rngs::StdRng, SeedableRng};

type Wots = ConstantCompositionWinternitz20;

#[test]
fn rank_boundaries_cover_exactly_the_160_bit_encoder_image() {
    let capacity =
        BigUint::parse_bytes(b"1514202802528191317310959056853549737574400000000", 10).unwrap();
    assert_eq!(Wots::codeword_count(), capacity);
    let boundary = BigUint::one() << 160usize;
    for value in [
        BigUint::zero(),
        BigUint::one(),
        &boundary - BigUint::one(),
        boundary.clone(),
        &capacity - BigUint::one(),
    ] {
        let digits = unrank(value.clone());
        assert_eq!(rank(&digits).unwrap(), value);
        if value < boundary {
            let message = Wots::decode_message(&digits).unwrap();
            assert_eq!(BigUint::from_bytes_be(&message), value);
            assert_eq!(Wots::encode_message(&message), digits);
        } else {
            assert_eq!(
                Wots::decode_message(&digits),
                Err(InvalidConstantCompositionEncoding)
            );
        }
    }

    let sorted: Vec<u8> = COMPOSITION
        .iter()
        .enumerate()
        .flat_map(|(digit, &count)| core::iter::repeat_n(digit as u8, count as usize))
        .collect();
    assert_eq!(Wots::encode_message(&[0; 20]).as_slice(), sorted);
    assert_eq!(Wots::decode_message(&sorted).unwrap(), [0; 20]);
    let mut wrong_composition = sorted.clone();
    wrong_composition[0] = 1;
    let mut invalid_digit = sorted.clone();
    invalid_digit[0] = RADIX as u8;
    let mut too_many = sorted.clone();
    too_many.push(0);
    for invalid in [
        &sorted[..CHAINS - 1],
        wrong_composition.as_slice(),
        invalid_digit.as_slice(),
        too_many.as_slice(),
    ] {
        assert_eq!(
            Wots::decode_message(invalid),
            Err(InvalidConstantCompositionEncoding)
        );
    }
}

#[test]
fn deterministic_messages_roundtrip_without_search() {
    let mut rng = StdRng::seed_from_u64(0xc0_6d_05_17_10_20);
    for _ in 0..256 {
        let mut message = [0; 20];
        rng.fill_bytes(&mut message);
        let digits = Wots::encode_message(&message);
        assert_eq!(Wots::decode_message(&digits).unwrap(), message);
        for (digit, &count) in COMPOSITION.iter().enumerate() {
            assert_eq!(
                digits
                    .iter()
                    .filter(|&&value| value as usize == digit)
                    .count(),
                count as usize
            );
        }
    }
}

#[test]
fn encoded_message_attains_the_exact_maximum_serialized_witness_size() {
    // Independent multiset rank: the lexicographically first assignment with
    // key zero in the implicit maximum group. Every emitted selector is nonzero.
    let message = [
        0xbd, 0x73, 0x6e, 0x13, 0x85, 0x1a, 0x95, 0x81, 0x86, 0x0e, 0x65, 0x5a, 0x5f, 0x31, 0xf6,
        0xd5, 0xe4, 0, 0, 0,
    ];
    let signature = Wots::sign(Wots::signing_key_from_seed([0x71; 32]), &message);
    assert_eq!(signature.digits[0], MAX_DIGIT as u8);
    let witness = signature.to_witness();
    assert_eq!(witness.len(), 70);
    assert_eq!(witness.size(), 802);
    assert!(witness
        .to_vec()
        .chunks_exact(2)
        .all(|pair| pair[0].len() == 1));
}

// Golden values generated by the independent standard-library implementation in
// tests/vectors.py with seed [0x42; 32]. Hashes cover concatenated key-indexed
// commitments/nodes and the complete Bitcoin witness serialization respectively.
fn python_golden_profile<H: ChainHash, P: PreimageSize<H>>(
    expected_commitments: &str,
    expected_openings: [(&str, &str, usize); 2],
) {
    use bitcoin::{
        consensus::serialize,
        hashes::{sha256, Hash},
        hex::FromHex,
    };
    type Profile<H, P> = ConstantCompositionWinternitz20<H, P>;
    let key = Profile::<H, P>::signing_key_from_seed([0x42; 32]);
    let public_key = Profile::<H, P>::public_key(&key);
    let commitments: Vec<u8> = public_key
        .commitments()
        .iter()
        .flat_map(|value| value.as_ref().iter().copied())
        .collect();
    assert_eq!(
        sha256::Hash::hash(&commitments).to_string(),
        expected_commitments
    );
    let messages = [
        ("00254a6f94b9de03284d7297bce1062b50759abf", "00020f110a0e1517010318181214180f060c1814130517181818100d17080407181312181610181816180916181511180b"),
        ("bd736e13851a9581860e655a5f31f6d5e4000000", "18000102030405060708090a0b0c0d0e0f0f10101111121213131414151516161617171718181818181818181818181818"),
    ];
    for ((message_hex, digits_hex), (expected_nodes, expected_witness, expected_size)) in
        messages.into_iter().zip(expected_openings)
    {
        let message = <[u8; 20]>::from_hex(message_hex).unwrap();
        let signature =
            Profile::<H, P>::sign(Profile::<H, P>::signing_key_from_seed([0x42; 32]), &message);
        assert_eq!(
            signature.digits().as_slice(),
            Vec::<u8>::from_hex(digits_hex).unwrap()
        );
        assert_eq!(
            Profile::<H, P>::decode_message(signature.digits()).unwrap(),
            message
        );
        let nodes: Vec<u8> = signature
            .chain_values()
            .iter()
            .flat_map(|value| value.as_ref().iter().copied())
            .collect();
        assert_eq!(sha256::Hash::hash(&nodes).to_string(), expected_nodes);
        let witness = signature.to_witness();
        assert_eq!(witness.len(), Profile::<H, P>::WITNESS_DATA_ITEMS);
        let serialized = serialize(&witness);
        assert_eq!(serialized.len(), expected_size);
        assert_eq!(serialized.len(), witness.size());
        assert_eq!(
            sha256::Hash::hash(&serialized).to_string(),
            expected_witness
        );
    }
}

#[test]
fn independent_python_vectors_match_all_hash_and_preimage_profiles() {
    use crate::signatures::winternitz::{FullWidth, Sha256, Sha256Hash160};
    python_golden_profile::<Hash160, Preimage16>(
        "9fff500c54de531006775a193fe0908f753745947b7e40e6b1780569da1854de",
        [
            (
                "1cc5fc18b4a6f0f2426fe0fdbca755564947c7e96652a6c3d2b97c339efe0d6d",
                "dba346a3df3fb754a033aaab291a8dfe89b3acd2297bc6b25e93868231bdc1d0",
                796,
            ),
            (
                "4cfb937b16aa2f231cd2a654779a990a96894e349f4785e410fd1ba5bd0348f4",
                "52607302f6cd23825fcb05c3924ff8903d07f6149c1f7f5e14c86f57d1d69303",
                802,
            ),
        ],
    );
    python_golden_profile::<Hash160, FullWidth>(
        "906ebc375969dce3fdf3accda15346ea3f15250eae3adcc897afae60e6af9fc8",
        [
            (
                "d51433e6c662aa39d476641339f7f1caf6a9691e9c6f042b74e97b510ef68699",
                "6914bddb797eea6a83e8d1b07079f0a41f87400946a8031514601450c44e38b1",
                800,
            ),
            (
                "1fd9489211220ca8cc2c60310bd37a09908459025d7aa14ffaa507f2d130fa6b",
                "ddafe85c73bf6bac95d0bd991705c9293716f0f5dc4fd3b7d9ee1903f827b3fe",
                806,
            ),
        ],
    );
    python_golden_profile::<Sha256, Preimage16>(
        "99f1b7a3e64af0e5aa45ccd4d78789ff88da68bdd1aefd8419c9d36deb175f19",
        [
            (
                "0393d40e7fb90a96ae83d3fb7c8a3c2a840ae44ae26a26e5085db530a3a91e55",
                "8ebe3b6936e867d0da94ff834cfd8306a8e6e3751d6b95c13084902fa9d0590e",
                1204,
            ),
            (
                "f04b6e9acbfd0c4a8c3e903905775d8828627e43f1caba51249c6e8578df3333",
                "0848f0dfe459e312224a679291fd8c2d26cc973a203a2de48deec98f9be3599f",
                1210,
            ),
        ],
    );
    python_golden_profile::<Sha256, FullWidth>(
        "941768bfda7f93bd20f3319512bcaa638d4c0f2cc63a9e95a6329029478bf5bf",
        [
            (
                "06685ea9714d302e2aa9a3367679f31400f3781abff57b906cc173ead74d7424",
                "a6880cd3d0e673c64cdf34641b257494fa930931ae208a798b1282e2216844a7",
                1220,
            ),
            (
                "02d8a58a26d564be6e790bea5f79fd48ea4efe1117b7e548f4430915eb8fe0e8",
                "7150fefa2852b7eaef807d21114de29542df5c20fc149152dde09493322d38c0",
                1226,
            ),
        ],
    );
    python_golden_profile::<Sha256Hash160, Preimage16>(
        "bcb1f9a158fe0c55f5e6535e80970328012eea4e6c982ec1ae38054217e10f0a",
        [
            (
                "cee7c9d54dcdac45bf0e3cd772b8f87f3ccd3530acd3255f6d4670a0061a3357",
                "3100e9c5862f45e4633c66eb5d0a7b1d4d5a60c57faf6f296fc94ec21718d372",
                1204,
            ),
            (
                "d331adf18be64b75559cf01ddaa553c68b8a7ee5c44e2e1443a41df0776b4755",
                "7c5805e83d0e4fa0c80abaf6ca4f3bb8b75adb652fac18fdc30143e746d280ae",
                1210,
            ),
        ],
    );
    python_golden_profile::<Sha256Hash160, FullWidth>(
        "18887bf6f179c9d1a8482b3098267c3e6241ea4a3a0315bf138965fe0109fd28",
        [
            (
                "bc6f82cd6721e87ebfc462dce62b9dd2b2463fa3facfaccdc143cc9ea0900f19",
                "940627e35863304b180a813ded5c34d029444ddf3980bbc41556cd2a1ffdf065",
                1220,
            ),
            (
                "19bd9ac8ee166edeb1894cd09390007f911a5b370ae0626db42864430c9c6492",
                "a0b688f2e5bf924970ca1b16034bea700af2a679ad501fa29dfcea7d98efce97",
                1226,
            ),
        ],
    );
}
